In [1]:
from ias.Datasets import Iris
from ias.DecisionTrees.CartDecisionTree import CartDecisionTree
from ias.Metrics import accuracy_score, confusion_matrix, show_confusion_matrix

In [2]:
import numpy as np

In [3]:
indices = np.arange(len(Iris.attributes))
np.random.shuffle(indices)
train_size = int(len(Iris.attributes)*2/3)

train_i = indices[:train_size]
train_x = Iris.attributes[train_i]
train_y = Iris.labels[train_i]

test_i = indices[train_size:]
test_x = Iris.attributes[test_i]
test_y = Iris.labels[test_i]

In [6]:
t = CartDecisionTree()
t.fit(train_x, train_y)
t.show(Iris.features_names, Iris.class_names)

[[5.8 2.7 5.1 1.9]
 [5.4 3.  4.5 1.5]
 [5.5 2.6 4.4 1.2]
 [6.2 2.2 4.5 1.5]
 [6.4 3.2 5.3 2.3]
 [6.8 3.2 5.9 2.3]
 [5.1 3.8 1.6 0.2]
 [6.8 2.8 4.8 1.4]
 [5.  3.2 1.2 0.2]
 [6.4 3.2 4.5 1.5]
 [5.2 2.7 3.9 1.4]
 [4.6 3.2 1.4 0.2]
 [6.  2.9 4.5 1.5]
 [5.7 2.5 5.  2. ]
 [5.4 3.7 1.5 0.2]
 [7.7 3.  6.1 2.3]
 [5.7 3.8 1.7 0.3]
 [4.8 3.  1.4 0.1]
 [6.7 2.5 5.8 1.8]
 [6.3 2.8 5.1 1.5]
 [6.3 3.4 5.6 2.4]
 [5.4 3.4 1.7 0.2]
 [5.  3.  1.6 0.2]
 [6.9 3.2 5.7 2.3]
 [5.5 2.4 3.7 1. ]
 [6.1 3.  4.9 1.8]
 [5.8 2.7 5.1 1.9]
 [5.4 3.9 1.3 0.4]
 [6.4 2.7 5.3 1.9]
 [6.9 3.1 5.1 2.3]
 [7.9 3.8 6.4 2. ]
 [5.9 3.  4.2 1.5]
 [6.2 2.9 4.3 1.3]
 [5.  3.6 1.4 0.2]
 [6.  2.2 4.  1. ]
 [5.6 2.9 3.6 1.3]
 [5.5 2.4 3.8 1.1]
 [5.7 2.9 4.2 1.3]
 [5.7 4.4 1.5 0.4]
 [6.3 2.5 5.  1.9]
 [7.7 2.6 6.9 2.3]
 [5.4 3.4 1.5 0.4]
 [5.2 3.5 1.5 0.2]
 [6.7 3.1 4.4 1.4]
 [5.1 3.8 1.5 0.3]
 [5.3 3.7 1.5 0.2]
 [6.  2.7 5.1 1.6]
 [4.9 3.1 1.5 0.1]
 [4.9 2.5 4.5 1.7]
 [6.5 3.  5.8 2.2]
 [5.8 2.7 4.1 1. ]
 [6.6 2.9 4.6 1.3]
 [6.3 2.5 4.

FileExistsError: 

In [ ]:
show_confusion_matrix(confusion_matrix(Iris.class_number, test_y, t.predict(test_x)), Iris.class_names)
print(accuracy_score(test_y, t.predict(test_x)))